### ISSUE TITLE
Feature Request: dart analyze run against a sub directory in a monorepo - add SARIF support for Code Scanning paths

### ISSUE THREAD

**Issue by felickz** [advanced-security/dart-analyzer-sarif#6]
To avoid `preview unavailable`:
<img width="578" alt="image" src="https://github.com/advanced-security/dart-analyzer-sarif/assets/1760475/f909c2ac-41e1-45ec-a6b4-758778abb292">

when running dart analyze on a sub directory:  the path  used in the output relative to the directory working directory being scanned... ex: `dart analyze path/to/app` run with files in directory `path/to/app/lib/...` will have output:
```
  error - lib/views/auth_screen.dart:59:7 - The named parameter 'resizeToAvoidBottomPadding' isn't defined. Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'resizeToAvoidBottomPadding'. - undefined_named_parameter
   info - lib/models/session_token.dart:2:10 - Name non-constant identifiers using lowerCamelCase. - non_constant_identifier_names
```

# Workaround
- edit the sarif to properly contain the location paths relative to the source root using [sarif-toolkit:relative paths patcher](https://github.com/advanced-security/sarif-toolkit/blob/main/relativepaths/README.md)

```yml

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: Dart Analyze
        run: dart analyze path/to/app > dart_analyze.txt || true
      - name: Dart Analyze to SARIF
        uses: advanced-security/dart-analyzer-sarif@main
        with:
          input: dart_analyze.txt
          output: dart_analyze.sarif
      # This tools allows users to update broken SARIF files that have relative paths that aren't based on the root GitHub Repository folder.
      - uses: advanced-security/sarif-toolkit/relativepaths@main
        with:
          # SARIF File / Directory location
          sarif: "./dart_analyze.sarif"
          # Working Directory (sub folder of the working directory)
          working: "path/to/app"
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: dart_analyze.sarif
```
